import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-4 sm:px-[5vw] md:px-[7vw] lg:px-[4vw]">
        <AuthProvider>
          {children}
        </AuthProvider>
        <script
          src="https://kit.fontawesome.com/79524683af.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
